Feature/vote 320 cypress test
usagov/vote-gov-nvrf-app pull request #62
Opened 2023-10-20 19:21 UTC by clmedders

2023-10-20 19:32 UTC, clmedders commented
I merged in a branch that Mandy had for a form fix... let me know if I need to fix any commits!

2023-10-20 23:16 UTC, rayestrada requested changes

2023-10-20 23:16 UTC, rayestrada commented on testing/cypress/e2e/workFlow/alaska.cy.js
@clmedders I would like to see a separate file for testing values. I remember Nehemiah showing us a JSON or YML file that he used to populate the content. This way we can vary the values or replacement them easily in one place if needed.

2023-10-20 23:16 UTC, rayestrada commented on testing/cypress/e2e/workFlow/alaska.cy.js
This could also let us to have 1 test for the form and not require a test for each state.

2023-10-23 18:04 UTC, clmedders commented on testing/cypress/e2e/workFlow/alaska.cy.js
updated with a `data.json` to hold the content... this is a good move I thought you couldn't use it as text and only for validation but have made that file so if we update one it will update all. I also made them based on the template but if that is not a good path either let me know!

2023-10-23 23:16 UTC, rayestrada approved these changes
This is a great start!

2023-10-23 23:16 UTC, merged